# Construct URL from Railway env vars

app.frontend.url=https://geocode-frontend.smartgeocode.io
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# --- CHANGE ONLY THIS SECTION (LOGGING) ---
# Set Root to INFO to stop the flood
logging.level.root=INFO
# Silence the autoconfigure noise
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.level.org.springframework.boot.autoconfigure.logging=ERROR
# Keep SQL logs so we can see table creation
logging.level.org.hibernate.SQL=DEBUG